### ISSUE TITLE
fatal: unsafe repository ('/github/workspace' is owned by someone else)

### ISSUE THREAD

**Issue by jinek** [ad-m/github-push-action#113]
At some moment it started to give this error
```
Push to branch ***************
fatal: unsafe repository ('/github/workspace' is owned by someone else)
To add an exception for this directory, call:

	git config --global --add safe.directory /github/workspace
```

**Comment by ZPascal** [comment]
@jinek Please switch the used version of the GitHub push action to ad-m/github-push-action@master. That should solve your issue, because the fix is already implemented [there](https://github.com/ad-m/github-push-action/commit/6defe3bd9f0a0846636a7d99ab96ccc75f2c858b).

**Comment by jinek** [comment]
Thank you a lot for fast response. Please, feel free to close this issue or may be better to keep it open others to see the solution?

**Comment by ZPascal** [comment]
Hi @jinek, I'll prepare a PR to update the documentation and make it more transparent that a version change is necessary.

**Comment by supersciencegrl** [comment]
Thank you so much for this! Really helpful for my cron repo updates.

**Comment by ZPascal** [comment]
Hi @jinek, I think the issue is solved. Can we close the it?

**Comment by jinek** [comment]
> Hi @jinek, I think the issue is solved. Can we close it?

Solved. Thank you!
