### ISSUE TITLE
No push being performed - Everything up-to-date

### ISSUE THREAD

**Issue by javixeneize** [ad-m/github-push-action#126]
Hi

I am trying to do a bumpversion in my workflow and pushing the changes with your action to the branch after updating the version.

However, when trying to push the changes, it fails. It says everything is up to date, but it isnt. In this example you can see the content in the workflow is different to the one in the branch, but it doesnt push the changes

https://github.com/javixeneize/yasca/runs/6539545361?check_suite_focus=true

Any idea what might be. the problem?

Thanks

**Comment by ZPascal** [comment]
Hi @javixeneize, I think you missed adding and committing your changes. You can find a working example [here](https://github.com/ZPascal/grafana_dashboard_templater/blob/main/.github/workflows/pull-request-checks.yml#L106-L109).

**Comment by javixeneize** [comment]
Ah right, I added and removed lots of steps so probably missed it. Thanks!
