### ISSUE TITLE
update to node16

### ISSUE THREAD

**Issue by renperez-cpi** [ad-m/github-push-action#141]
hi @ad-m 
any chance we can upgrade from node12 to node16?
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: ad-m/github-push-action

**Comment by ZPascal** [comment]
Hi @renperez-cpi, the version upgrade is already handled with the following [PR](https://github.com/ad-m/github-push-action/pull/140). I'll close the issue now.
