### ISSUE TITLE
Node.js 12 -> Node.js 16 ?

### ISSUE THREAD

**Issue by ubaldot** [ad-m/github-push-action#144]
I am using this action (v0.6.0) and I get this warning from GitHub:

`Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: ad-m/github-push-action`

Shall I be worried? :)

**Comment by ZPascal** [comment]
@ubaldot Do you have further questions, or can we close the issue?

**Comment by ubaldot** [comment]
I closed it! Thanks for the support!
