### ISSUE TITLE
Maybe we should release a new version to use node16

### ISSUE THREAD

**Issue by qhy040404** [ad-m/github-push-action#146]
Even a patch version.

**Comment by ZPascal** [comment]
Hi @qhy040404, you can use the `ad-m/github-push-action@master` version to consume the newest version. **FYI:** I've also got an open [PR](https://github.com/ad-m/github-push-action/pull/145) to create and handle new versions.

**Comment by ZPascal** [comment]
Hi @qhy040404, can we close the issue?
