### ISSUE TITLE
discard gh-pages history

### ISSUE THREAD

**Issue by iltommi** [ad-m/github-push-action#147]
Hi,
I'm converting my doc from travis to github actions.
Every time I push to master branch, I have an action that builds the documentation that I want to push on the `gh-pages` branch. But I don't care about keeping the doc history (this will increase the clone of the main repo).

I Travis I just needed to add a `keep-history: false`

Do you know how to achieve this?

Thanks a lot

**Comment by ZPascal** [comment]
Hi @iltommi, I've quickly checked the corresponding implementation [here](https://github.com/webknjaz/dpl/pull/1/files) and I can communicate that we do not support such an case.

**Comment by iltommi** [comment]
Thanks!
