### ISSUE TITLE
[Security] Update to Node.js 16

### ISSUE THREAD

**Issue by kevinmatthes** [ad-m/github-push-action#148]
Hello, @ad-m,

Thank you for this GitHub Action!

When using it in my repositories, I noticed the warning in the Actions tab that the latest version v0.6.0 still uses the outdated Node.js version 12.  Please update to Node.js version 16 in order to both prevent serious security issues and ensure this Action to continue to work appropriately.

**Comment by ZPascal** [comment]
Hi @kevinmatthes,

I recommend switching to `ad-m/github-push-action@master` as version to solve the issue.

**Comment by kevinmatthes** [comment]
Thank you for your suggestion, @ZPascal!  In the long term, is a new release planned?

**Comment by ZPascal** [comment]
Hi Kevin, from my side a new release is planned and to also pin major version e.g. v3 and integrate the corresponding matching minor versions directly inside the tagged major version. I've already prepared a [PR](https://github.com/ad-m/github-push-action/pull/145) for it, and I'm currently needing a review.

**Comment by kevinmatthes** [comment]
@ZPascal

Thanks!  This solves this issue from my side!
