### ISSUE TITLE
Prompt "remote: Invalid username or password." when entering the"Push"line operation 

### ISSUE THREAD

**Issue by xianyongjian080402** [ad-m/github-push-action#150]
我在一个组织仓库进行push操作的出现“remote: Invalid username or password.” error，我不知道怎么办

error截图：
![截屏2023-01-27 21 25 51](https://user-images.githubusercontent.com/70191815/215097918-00ea1ea3-8c17-4b67-9d02-fa1e79e9e399.png)
我确定仓库URL没有任何的问题，这是我Actions的部分代码：
```
GitPushAndRelease:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: Update
    steps:
    - name: Commit
      id: commit
      run: |
        git config --global user.email xianyongjian080402@126.com
        git config --global user.name xianyongjian080402-Bot
        git status
        git add .
        git commit -m "[Bot]-[Update ZipFile]"
      continue-on-error: true
      
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.BOTTOKEN }}
```

我在仓库环境(Update)中设置了环境秘密：
![image](https://user-images.githubusercontent.com/70191815/215098615-0140fe6c-057d-4391-a2bb-d250edcf313e.png)

由于组织仓库无法打开这个选项，导致我只能使用自己的token
![截屏2023-01-27 21 31 48](https://user-images.githubusercontent.com/70191815/215099055-7f8e336b-4380-4c9b-9a75-f3fb802d457f.png)

这个代码在我自己的仓库中没有问题，除了`${{ secrets.GITHUB_TOKEN}}`不同以外，其他代码都是一样的，我不知道如何修复这个问题，希望得到支持，谢谢！🙏

**Comment by ZPascal** [comment]
Hi @xianyongjian080402, if you want to push to the repository, you should specify the read & write access for the token. In general, it's also necessary that the Token/ User got access to the repository and added to the secrets of the repository.

**Chinese language (translated):**
你好 @xianyongjian080402，如果你想推送到版本库，你应该指定令牌的读写权限。一般来说，也需要令牌/用户获得对版本库的访问权，并添加到版本库的机密中。

**Comment by xianyongjian080402** [comment]
> Hi @xianyongjian080402, if you want to push to the repository, you should specify the read & write access for the token. In general, it's also necessary that the Token/ User got access to the repository and added to the secrets of the repository.
> 
> **Chinese language (translated):** 你好 @xianyongjian080402，如果你想推送到版本库，你应该指定令牌的读写权限。一般来说，也需要令牌/用户获得对版本库的访问权，并添加到版本库的机密中。

🤔，我确认令牌的读写权限没有问题，我把我的小号给了仓库的管理员权限，依旧不行。我确认我的`${{ secrets.BOTTOKEN }}`没有任何问题，因为在后续的发布版本的操作中，也使用了`${{ secrets.BOTTOKEN }}`，并且没有报错

**Comment by xianyongjian080402** [comment]
![截屏2023-01-28 09 11 12](https://user-images.githubusercontent.com/70191815/215233373-579d34cd-fefe-48e2-aa54-ffe0e78b7943.png)

**Comment by xianyongjian080402** [comment]
#96

找到了一个类似问题，我去联系我的组织打开这个设置
![截屏2023-01-28 09 19 31](https://user-images.githubusercontent.com/70191815/215233836-b63356a0-832b-40d3-a486-947482ca7f7c.png)

**Comment by xianyongjian080402** [comment]
![截屏2023-01-28 13 53 05](https://user-images.githubusercontent.com/70191815/215248736-51b109b2-a0e1-400e-bc22-cd3bca938cf1.png)
更改之后仍然失败

**Comment by xianyongjian080402** [comment]
> ![截屏2023-01-28 13 53 05](https://user-images.githubusercontent.com/70191815/215248736-51b109b2-a0e1-400e-bc22-cd3bca938cf1.png) 更改之后仍然失败

更改之后把`${{ secrets.BOTTOKEN }}`改成`${{ secrets.GITHUB_TOKEN}}`后依然失败

**Comment by ZPascal** [comment]
Hi @xianyongjian080402, have you ever manually tried to get access to the repository with the bot token you generated yourself? The GitHub is not a GitHub Enterprise instance, right?

**Chinese language (translated):**
你好 @xianyongjian080402，你有没有尝试过用自己生成的机器人令牌手动访问版本库？这个GitHub不是一个GitHub企业实例，对吗？

**Comment by xianyongjian080402** [comment]
> Hi @xianyongjian080402, have you ever manually tried to get access to the repository with the bot token you generated yourself? The GitHub is not a GitHub Enterprise instance, right?
> 
> **Chinese language (translated):** 你好 @xianyongjian080402，你有没有尝试过用自己生成的机器人令牌手动访问版本库？这个GitHub不是一个GitHub企业实例，对吗？

a,我没太理解，您是说，可能是我令牌的问题吗？我令牌把所有权限都点上了，然后我还试过重新生成，但是都没有用，我的私人令牌应该没有问题，因为在后面使用`ncipollo/release-action@v1.12.0`进行版本发布，使用`${{ secrets.BOTTOKEN }}`是没有任何问题的，所以我很疑惑🤔

**Comment by ZPascal** [comment]
Hi @xianyongjian080402

I want to make sure the token is working correctly and want you to make a dummy commit to the repository with the token.

I suspect that you are using the [wrong user](https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables), since we are using the [GITHUB_ACTOR](https://github.com/ad-m/github-push-action/blob/0fafdd62b84042d49ec0cb92d9cac7f7ce4ec79e/start.sh#L46) variable as the username in the action. So I think you are using the wrong user with your own token and the variable needs to be adjusted accordingly.

Also, to be on the safe side, I would like you to let me know if the product is a public GitHub or a self-hosted GitHub Enterprise instance?

Chinese language (translated):
我想确定令牌是否正常工作，希望你用令牌向版本库做一个假的提交。

我怀疑你用错了用户，[因为我们](https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables)在行动中使用[GITHUB_ACTOR](https://github.com/ad-m/github-push-action/blob/0fafdd62b84042d49ec0cb92d9cac7f7ce4ec79e/start.sh#L46)变量作为用户名。所以我认为你使用了错误的用户和你自己的令牌，变量需要做相应的调整。

另外，为了安全起见，我希望你能让我知道该产品是公共的Github还是自我托管的Github企业实例？

**Comment by xianyongjian080402** [comment]
emmm，我刚刚使用令牌进行了提交（由于我没有记录原来的令牌，所以我重新生成了一个），没有出现任何问题，截屏如下：
![截屏2023-01-30 19 37 32](https://user-images.githubusercontent.com/70191815/215466882-708bebf9-7ac1-43ee-9e33-0e23647c47cf.png)

**Comment by xianyongjian080402** [comment]
存储库：https://github.com/SkyWorldStudio/MinecraftAssetsFileGet

**Comment by xianyongjian080402** [comment]
我觉得问题还是出在token上，因为我尝试使用命令（不使用`ad-m/github-push-action`）进行提交，报错仍然不变

**Comment by xianyongjian080402** [comment]
我再次更改了私密变量的token，仍然报错，这么说，那就是命令有问题

**Comment by xianyongjian080402** [comment]
> 我再次更改了私密变量的token，仍然报错，这么说，那就是命令有问题

因为我在终端就没有任何问题

**Comment by ZPascal** [comment]
Hi @xianyongjian080402,

Could you please check if this [adaption](https://github.com/ad-m/github-push-action/issues/151#issuecomment-1427057311) of your checkout step solves your case? Be aware, to use the same personal access token as on the GitHub Push Action.

Otherwise, I'll start to reproduce your case on my side and will debug it.

**Chinese language (translated):**
你能不能检查一下你的结账步骤的这个[改编](https://github.com/ad-m/github-push-action/issues/151#issuecomment-1427057311)是否解决了你的问题？请注意，要使用与GitHub推送操作相同的个人访问令牌。

否则，我将开始在我这边重现你的情况并进行调试。

**Comment by xianyongjian080402** [comment]
> Hi @xianyongjian080402,
> 
> Could you please check if this [adaption](https://github.com/ad-m/github-push-action/issues/151#issuecomment-1427057311) of your checkout step solves your case? Be aware, to use the same personal access token as on the GitHub Push Action.
> 
> Otherwise, I'll start to reproduce your case on my side and will debug it.
> 
> **Chinese language (translated):** 你能不能检查一下你的结账步骤的这个[改编](https://github.com/ad-m/github-push-action/issues/151#issuecomment-1427057311)是否解决了你的问题？请注意，要使用与GitHub推送操作相同的个人访问令牌。
> 
> 否则，我将开始在我这边重现你的情况并进行调试。

I'm so sory… I just saw…

I changes action config file ,please wait for active completion.

(Chinese):
抱歉，我刚看到……
我更改了自动化的配置文件，请等待自动化完成

**Comment by xianyongjian080402** [comment]
> > Hi @xianyongjian080402,
> > Could you please check if this [adaption](https://github.com/ad-m/github-push-action/issues/151#issuecomment-1427057311) of your checkout step solves your case? Be aware, to use the same personal access token as on the GitHub Push Action.
> > Otherwise, I'll start to reproduce your case on my side and will debug it.
> > **Chinese language (translated):** 你能不能检查一下你的结账步骤的这个[改编](https://github.com/ad-m/github-push-action/issues/151#issuecomment-1427057311)是否解决了你的问题？请注意，要使用与GitHub推送操作相同的个人访问令牌。
> > 否则，我将开始在我这边重现你的情况并进行调试。
> 
> I'm so sory… I just saw…
> 
> I changes action config file ,please wait for active completion.
> 
> (Chinese): 抱歉，我刚看到…… 我更改了自动化的配置文件，请等待自动化完成

emmm, active out put:
```
Warning: Unexpected input(s) 'github_token', valid inputs are ['repository', 'ref', 'token', 'ssh-key', 'ssh-known-hosts', 'ssh-strict', 'persist-credentials', 'path', 'clean', 'fetch-depth', 'lfs', 'submodules', 'set-safe-directory', 'github-server-url']
Run actions/checkout@v3
  with:
    github_token: ***
    repository: SkyWorldStudio/MinecraftAssetsFileGet
    token: ***
    ssh-strict: true
    persist-credentials: true
    clean: true
    fetch-depth: 1
    lfs: false
    submodules: false
    set-safe-directory: true
Syncing repository: SkyWorldStudio/MinecraftAssetsFileGet
Getting Git version info
  Working directory is '/home/runner/work/MinecraftAssetsFileGet/MinecraftAssetsFileGet'
  /usr/bin/git version
  git version [2](https://github.com/SkyWorldStudio/MinecraftAssetsFileGet/actions/runs/4273040998/jobs/7439044376#step:5:2).[3](https://github.com/SkyWorldStudio/MinecraftAssetsFileGet/actions/runs/4273040998/jobs/7439044376#step:5:3)9.2
Copying '/home/runner/.gitconfig' to '/home/runner/work/_temp/d6f47842-a3c2-4bf5-8a82-1db0f84d310c/.gitconfig'
Temporarily overriding HOME='/home/runner/work/_temp/d6f47842-a3c2-4bf5-8a82-1db0f84d310c' before making global git config changes
Adding repository directory to the temporary git global config as a safe directory
/usr/bin/git config --global --add safe.directory /home/runner/work/MinecraftAssetsFileGet/MinecraftAssetsFileGet
/usr/bin/git config --local --get remote.origin.url
https://github.com/SkyWorldStudio/MinecraftAssetsFileGet
Removing previously created refs, to avoid conflicts
  /usr/bin/git rev-parse --symbolic-full-name --verify --quiet HEAD
  refs/heads/main
  /usr/bin/git checkout --detach
  HEAD is now at 2cb7fbe [Bot]-[Update ZipFile]
  /usr/bin/git branch --delete --force main
  Deleted branch main (was 2cb7fbe).
Cleaning the repository
  /usr/bin/git clean -ffdx
  Removing FileZip/
  /usr/bin/git reset --hard HEAD
  HEAD is now at 2cb7fbe [Bot]-[Update ZipFile]
Disabling automatic garbage collection
  /usr/bin/git config --local gc.auto 0
Setting up auth
  /usr/bin/git config --local --name-only --get-regexp core\.sshCommand
  /usr/bin/git submodule foreach --recursive sh -c "git config --local --name-only --get-regexp 'core\.sshCommand' && git config --local --unset-all 'core.sshCommand' || :"
  /usr/bin/git config --local --name-only --get-regexp http\.https\:\/\/github\.com\/\.extraheader
  http.https://github.com/.extraheader
  /usr/bin/git config --local --unset-all http.https://github.com/.extraheader
  /usr/bin/git submodule foreach --recursive sh -c "git config --local --name-only --get-regexp 'http\.https\:\/\/github\.com\/\.extraheader' && git config --local --unset-all 'http.https://github.com/.extraheader' || :"
  /usr/bin/git config --local http.https://github.com/.extraheader AUTHORIZATION: basic ***
Fetching the repository
  /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +87e6d33a006b9e2fa8ca221694debf8731a9fb74:refs/remotes/origin/main
  remote: Total 0 (delta 0), reused 0 (delta 0), pack-reused 0        
Determining the checkout info
Checking out the ref
  /usr/bin/git checkout --progress --force -B main refs/remotes/origin/main
  Warning: you are leaving 1 commit behind, not connected to
  any of your branches:
  
    2cb7fbe [Bot]-[Update ZipFile]
  
  If you want to keep it by creating a new branch, this may be a good time
  to do so with:
  
   git branch <new-branch-name> 2cb7fbe
  
  Switched to a new branch 'main'
  branch 'main' set up to track 'origin/main'.
/usr/bin/git log -1 --format='%H'
'87e6d33a006b9e2fa8ca22169[4](https://github.com/SkyWorldStudio/MinecraftAssetsFileGet/actions/runs/4273040998/jobs/7439044376#step:5:4)debf8[7](https://github.com/SkyWorldStudio/MinecraftAssetsFileGet/actions/runs/4273040998/jobs/7439044376#step:5:7)31a[9](https://github.com/SkyWorldStudio/MinecraftAssetsFileGet/actions/runs/4273040998/jobs/7439044376#step:5:9)fb74'
```

**Comment by xianyongjian080402** [comment]
No exception exits, but no commit is made

**Comment by jinek** [comment]
> I think you've used the [wrong parameter](https://github.com/actions/checkout/blob/ac593985615ec2ede58e132d2e21d2b1cbd6127c/action.yml#L12) inside the checkout action to specify the token. Please use only `token` instead of `github_token`.

When was it changed? I have `github_token` too, previously it worked.

**Comment by ZPascal** [comment]
@jinek You're currently talking about the `github-push-action` right? We're still using the parameter `github_token` to forward the token to the action. 

>update 2: in my case it was expired token. May be we could have a message for this case?

Do you have the real error message? I can add a hint to the documentation

**FYI:** @xianyongjian080402 used the wrong parameter inside the `checkout` action.

**Comment by xianyongjian080402** [comment]
> @jinek You're currently talking about the `github-push-action` right? We're still using the parameter `github_token` to forward the token to the action.
> 
> > update 2: in my case it was expired token. May be we could have a message for this case?
> 
> Do you have the real error message? I can add a hint to the documentation
> 
> **FYI:** @xianyongjian080402 used the wrong parameter inside the `checkout` action.

我尝试用自己时token，结果还是失败的(I tried to use my own token, the result is still failed )
配置文件(configuration file)
```
- name: Push changes
      uses: actions/checkout@v3
      with:
        github_token: ${{ secrets.BOTTOKEN }}
      continue-on-error: true
```
out put :
```
Warning: Unexpected input(s) 'github_token', valid inputs are ['repository', 'ref', 'token', 'ssh-key', 'ssh-known-hosts', 'ssh-strict', 'persist-credentials', 'path', 'clean', 'fetch-depth', 'lfs', 'submodules', 'set-safe-directory', 'github-server-url']
Run actions/checkout@v3
Syncing repository: SkyWorldStudio/MinecraftAssetsFileGet
Getting Git version info
  Working directory is '/home/runner/work/MinecraftAssetsFileGet/MinecraftAssetsFileGet'
  /usr/bin/git version
  git version [2](https://github.com/SkyWorldStudio/MinecraftAssetsFileGet/actions/runs/4324990118/jobs/7551750108#step:5:2).39.2
Copying '/home/runner/.gitconfig' to '/home/runner/work/_temp/1aea01f5-ce50-461c-a79e-c30bfb559c25/.gitconfig'
Temporarily overriding HOME='/home/runner/work/_temp/1aea01f5-ce50-461c-a79e-c30bfb559c25' before making global git config changes
Adding repository directory to the temporary git global config as a safe directory
/usr/bin/git config --global --add safe.directory /home/runner/work/MinecraftAssetsFileGet/MinecraftAssetsFileGet
/usr/bin/git config --local --get remote.origin.url
https://github.com/SkyWorldStudio/MinecraftAssetsFileGet
Removing previously created refs, to avoid conflicts
Cleaning the repository
Disabling automatic garbage collection
Setting up auth
Fetching the repository
Determining the checkout info
Checking out the ref
/usr/bin/git log -1 --format='%H'
'd43fa36036ebc7fef31c10685[14](https://github.com/SkyWorldStudio/MinecraftAssetsFileGet/actions/runs/4324990118/jobs/7551750108#step:5:15)53bfd6253[20](https://github.com/SkyWorldStudio/MinecraftAssetsFileGet/actions/runs/4324990118/jobs/7551750108#step:5:22)6a'
```

url:https://github.com/SkyWorldStudio/MinecraftAssetsFileGet/actions/runs/4324990118/jobs/7551750108

![截屏2023-03-04 02 11 27](https://user-images.githubusercontent.com/70191815/222795892-7185a264-41c8-4104-b83d-960994233832.png)

**Comment by ZPascal** [comment]
@xianyongjian080402 You are still using the wrong parameter inside the checkout action. Please switch it to only `token` and not `github_token`. thank you.

**Chinese language (translated):**
你仍然在结账动作中使用错误的参数。请改成只用`token`而不是`github_token`。谢谢。

**Comment by xianyongjian080402** [comment]
> @xianyongjian080402您仍在结帐操作中使用错误的参数。请将其切换为 only`token`和 not `github_token`。谢谢。
> 
> **Chinese language (translated):** 你仍然在结账活动中使用错误的参数。请改成只用`token`而不是`github_token`。谢谢。



> @xianyongjian080402 You are still using the wrong parameter inside the checkout action. Please switch it to only `token` and not `github_token`. thank you.
> 
> **Chinese language (translated):** 你仍然在结账动作中使用错误的参数。请改成只用`token`而不是`github_token`。谢谢。

o,sorry…

Run again with the changes

```
Run actions/checkout@v3
Syncing repository: SkyWorldStudio/MinecraftAssetsFileGet
Getting Git version info
Copying '/home/runner/.gitconfig' to '/home/runner/work/_temp/3abb0873-0221-4d4f-a3c7-e8f90973bc41/.gitconfig'
Temporarily overriding HOME='/home/runner/work/_temp/3abb0873-0221-4d4f-a3c7-e8f90973bc41' before making global git config changes
Adding repository directory to the temporary git global config as a safe directory
/usr/bin/git config --global --add safe.directory /home/runner/work/MinecraftAssetsFileGet/MinecraftAssetsFileGet
/usr/bin/git config --local --get remote.origin.url
https://github.com/SkyWorldStudio/MinecraftAssetsFileGet
Removing previously created refs, to avoid conflicts
Cleaning the repository
Disabling automatic garbage collection
Setting up auth
Fetching the repository
Determining the checkout info
Checking out the ref
/usr/bin/git log -1 --format='%H'
'6084ac98040f[48](https://github.com/SkyWorldStudio/MinecraftAssetsFileGet/actions/runs/4326147562/jobs/7554505321#step:5:55)3c7ce77fac6c8f08e0bfffb4a9'
```

url:
https://github.com/SkyWorldStudio/MinecraftAssetsFileGet/actions/runs/4326147562/jobs/7554505321

**Comment by ZPascal** [comment]
You're using the wrong actions. It's necessary to check out the corresponding repository beforehand and after that step git push your changes to the repository.

**You can the following code snippet to solve your problem:**

```yml      
    - name: Checkout the repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.BOTTOKEN }}

    - name: Commit
      run: |
        git config --global user.email xianyongjian080402@126.com
        git config --global user.name xianyongjian08040202
        git add .
        git commit -m "[Bot]-[Update ZipFile]"

    - name: Push the change
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.BOTTOKEN }}
        branch: ${{ github.head_ref }}

    - name: Upload artifact to release
      uses: ncipollo/release-action@v1.12.0
      with:
        name: File_Update_Release
        allowUpdates: true
        replacesArtifacts: true
        tag: BuildRelease
        token: ${{ secrets.BOTTOKEN }}
        artifacts: FileZip/*, ShaAndPath.json

```

**Comment by xianyongjian080402** [comment]
OKKK! 我按照您的指示更改了配置文件后，又排查出了一个问题，现在可以正常提交了，感谢！

在 https://github.com/SkyWorldStudio/MinecraftAssetsFileGet/commit/f7a4182f1cf07f1ada03f43851c5d07282cf54d2 中无法正常提交的原因貌似因为是错误的使用了`actions/checkout@v3`签出了存储库，这个操作删除了.git文件，导致git commit失败

**Comment by xianyongjian080402** [comment]
谢谢！

<img src="https://media1.giphy.com/media/dG0HsXfl09q9LTxOy1/giphy.gif"/>
