### ISSUE TITLE
Push another repo error 

### ISSUE THREAD

**Issue by totalo** [ad-m/github-push-action#151]
<img width="839" alt="image" src="https://user-images.githubusercontent.com/29777558/216306032-6dd5a03d-007e-42ce-999b-3d72a5bae573.png">

**Comment by totalo** [comment]
<img width="995" alt="image" src="https://user-images.githubusercontent.com/29777558/216310014-8c4f281a-6de7-4ccf-bd3d-0d6643913398.png">

**Comment by ZPascal** [comment]
> <img alt="image" width="839" src="https://user-images.githubusercontent.com/29777558/216306032-6dd5a03d-007e-42ce-999b-3d72a5bae573.png">

You've set up the SSH mode with the param `ssh:  true`. So you've also forwarded a deploy key or an ssh key?

**Comment by ZPascal** [comment]
> <img alt="image" width="995" src="https://user-images.githubusercontent.com/29777558/216310014-8c4f281a-6de7-4ccf-bd3d-0d6643913398.png">

if you want to use your personal token, it's necessary to owerwrite the default user. I've described it [here](https://github.com/ad-m/github-push-action/issues/150#issuecomment-1407767969).

**Comment by totalo** [comment]
> > <img alt="image" width="995" src="https://user-images.githubusercontent.com/29777558/216310014-8c4f281a-6de7-4ccf-bd3d-0d6643913398.png">
> 
> if you want to use your personal token, it's necessary to owerwrite the default user. I've described it [here](https://github.com/ad-m/github-push-action/issues/150#issuecomment-1407767969).

I think it's still an implementation issue. I used another action component and it worked.

**Comment by totalo** [comment]
<img width="553" alt="image" src="https://user-images.githubusercontent.com/29777558/216363684-fba4097b-b5c4-44ed-b98f-140948f00d7d.png">

**Comment by ZPascal** [comment]
> I think it's still an implementation issue. I used another action component and it worked.
I can implement a solution to overwrite the default user specified by **GITHUB** if needed.

> <img alt="image" width="553" src="https://user-images.githubusercontent.com/29777558/216363684-fba4097b-b5c4-44ed-b98f-140948f00d7d.png">
For my understanding the user action here overwrite this user. 

Did overwriting the user help you?

**Comment by totalo** [comment]
Thank you for your patience, but I understand it is not, I tried to configure my own account and use tokens, but also failed. Using another action component using my own account or github-action[bot] worked. Or based on our component, how should I configure if I want to push another repository?

The config:
<img width="724" alt="image" src="https://user-images.githubusercontent.com/29777558/216489820-9ca7726a-e8b1-4e74-965e-a5c1b16516db.png">

The error：
<img width="895" alt="image" src="https://user-images.githubusercontent.com/29777558/216489948-e85d4ee7-d237-4e18-9d62-ed09f8513523.png">


Another point is that configuring users via git config doesn't seem to work for components.

**Comment by ZPascal** [comment]
>Thank you for your patience, but I understand it is not, I tried to configure my own account and use tokens, but also failed. 

No problem.  Let's fix your case :+1: 

>Using another action component using my own account or github-action[bot] worked. 

If you are using the `github-action[bot]` user, you used the default `GITHUB_TOKEN`, right?

>Or based on our component, how should I configure if I want to push another repository?
I think the corresponding configuration below should work for my understanding. I'll follow this case up and start to build a reproducible case on my side.

>Another point is that configuring users via git config doesn't seem to work for components.

As I already mentioned, we're not using the corresponding specified git config user. We're using the `GITHUB_ACTOR` environment variable, specified by the action system, that user[ represents the corresponding user](https://docs.github.com/en/enterprise-cloud@latest/actions/learn-github-actions/variables#default-environment-variables) who initiated the GitHub Action. 

I think it's maybe necessary to overwrite this environment variable. I've placed an **untested** example below.

```
 - name: Push changes
   uses: ad-m/github-push-action@master
   with:
     github_token: <token>
     branch: master
     repository: <repository>
     force: true
     github_url: <url>
     directory: .
   env:
      GITHUB_ACTOR: <user user>
```

**Comment by totalo** [comment]
> > Thank you for your patience, but I understand it is not, I tried to configure my own account and use tokens, but also failed.
> 
> No problem. Let's fix your case 👍
> 
> > Using another action component using my own account or github-action[bot] worked.
> 
> If you are using the `github-action[bot]` user, you used the default `GITHUB_TOKEN`, right?

Yes, the token is the same. but failed.

> 
> > Or based on our component, how should I configure if I want to push another repository?
> > I think the corresponding configuration below should work for my understanding. I'll follow this case up and start to build a reproducible case on my side.
> 
> > Another point is that configuring users via git config doesn't seem to work for components.
> 
> As I already mentioned, we're not using the corresponding specified git config user. We're using the `GITHUB_ACTOR` environment variable, specified by the action system, that user[ represents the corresponding user](https://docs.github.com/en/enterprise-cloud@latest/actions/learn-github-actions/variables#default-environment-variables) who initiated the GitHub Action.
> 
> I think it's maybe necessary to overwrite this environment variable. I've placed an **untested** example below.
> 
> ```
>  - name: Push changes
>    uses: ad-m/github-push-action@master
>    with:
>      github_token: <token>
>      branch: master
>      repository: <repository>
>      force: true
>      github_url: <url>
>      directory: .
>    env:
>       GITHUB_ACTOR: <user user>
> ```
Thank you, i has try it, but it does not work.
<img width="857" alt="image" src="https://user-images.githubusercontent.com/29777558/216804122-c9f6bd7e-2160-4d0f-86a9-a80c671365cd.png">

**Comment by ZPascal** [comment]
I've reproduced the issue on [my side](https://github.com/ZPascal/test_origin_push_action/actions) and added a few debug variables inside a [special adapted version](https://github.com/ad-m/github-push-action/pull/156). To further analyze the issue, I've checked the functionality and at the end I've found an issue inside the documentation of the GitHub Action. 

I think that could be also your case, it's necessary to use the same token as inside Push Action inside the checkout otherwise, the action use at the end the GitHub service user specified by the checkout functionality.

Could you please execute your case again and adapt beforehand the checkout action like the following example? Thank you.

```yml
      - uses: actions/checkout@v3
        with:
          ...
          token: ${{ secrets.TOKEN }}
```

As a follow-up, I'll adjust the existing PR, adapt the documentation and a bit the code.

**Comment by totalo** [comment]
> I've reproduced the issue on [my side](https://github.com/ZPascal/test_origin_push_action/actions) and added a few debug variables inside a [special adapted version](https://github.com/ad-m/github-push-action/pull/156). To further analyze the issue, I've checked the functionality and at the end I've found an issue inside the documentation of the GitHub Action.
> 
> I think that could be also your case, it's necessary to use the same token as inside Push Action inside the checkout otherwise, the action use at the end the GitHub service user specified by the checkout functionality.
> 
> Could you please execute your case again and adapt beforehand the checkout action like the following example? Thank you.
> 
> ```yaml
>       - uses: actions/checkout@v3
>         with:
>           ...
>           token: ${{ secrets.TOKEN }}
> ```
> 
> As a follow-up, I'll adjust the existing PR, adapt the documentation and a bit the code.

Thank you, and It seems that the permission verification has passed, but there seems to be something wrong with the steps in the execution of push. It may need to clone the local execution machine first, overwrite the local generated file, and then add it to git for push.
<img width="820" alt="image" src="https://user-images.githubusercontent.com/29777558/218376194-b4e840eb-d5f8-4329-a456-930304c1c286.png">

**Comment by ZPascal** [comment]
I've tested it with a force push and it worked as expected. If this, is not possible for your case, I recommend cloning the other repository beforehand and move the file to do not break the history. If you need for such a case an example, feel free to notify me.

**Comment by totalo** [comment]
> I've tested it with a force push and it worked as expected. If this, is not possible for your case, I recommend cloning the other repository beforehand and move the file to do not break the history. If you need for such a case an example, feel free to notify me.

i has tested it.but aslo failed.
<img width="423" alt="image" src="https://user-images.githubusercontent.com/29777558/218398070-ba0e4647-0628-4bfb-be76-37a9a640f64b.png">

**Comment by ZPascal** [comment]
Can you please share the corresponding error message? I want to reproduce the case.

**Comment by totalo** [comment]
> Can you please share the corresponding error message? I want to reproduce the case.

```
To https://github.com/totalo/totalo.github.io.git
 ! [remote rejected] HEAD -> master (shallow update not allowed)
error: failed to push some refs to 'https://github.com/totalo/totalo.github.io.git'
Error: Invalid exit code: 1
    at ChildProcess.<anonymous> (/home/runner/work/_actions/ad-m/github-push-action/master/start.js:29:21)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1092:[16](https://github.com/totalo/website/actions/runs/4160303292/jobs/7197167984#step:6:17))
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5) {
  code: 1
}
Error: Invalid exit code: 1
    at ChildProcess.<anonymous> (/home/runner/work/_actions/ad-m/github-push-action/master/start.js:29:21)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
```

**Comment by ZPascal** [comment]
The interesting fact is the following sentence `shallow update not allowed`. Do you have used the` fetch-depth: 0` parameter inside the checkout action, like the following example? I think that's necessary for your corresponding case.

```
- uses: actions/checkout@v3
  with:
    ref: ${{ github.head_ref }}
    fetch-depth: 0
    token: ${{ secrets.PAT_TOKEN }}
```

**Comment by totalo** [comment]
> The interesting fact is the following sentence: `shallow update not allowed`. Do you have used the` fetch-depth: 0` parameter inside the checkout action, like the following example? I think that's necessary for your corresponding case.
> 
> ```
> - uses: actions/checkout@v3
>   with:
>     ref: ${{ github.head_ref }}
>     fetch-depth: 0
>     token: ${{ secrets.PAT_TOKEN }}
> ```

Thank you.It worked, but it seemed like the directory configuration wasn't working. It was pushing my source code up instead of the generated files.

**Comment by ZPascal** [comment]
Okay, is the corresponding added configuration [here](https://github.com/ad-m/github-push-action/issues/151#issuecomment-1414592237) still right and was it expected result?  At the end, the action only switches the directory and the git add is performed by yourselves.

**Comment by totalo** [comment]
> @totalo Okay, is the corresponding added configuration [here](https://github.com/ad-m/github-push-action/issues/151#issuecomment-1414592237) still right and was it the expected result? At the end, the action only switches the directory and the git add is performed by yourselves.

@ZPascal , Thank you. I'm sorry for the late reply. I didn't do `git add` on the new configuration. And finally just switch directories, right? There's no `git add`, did the component add it automatically for me

**Comment by ZPascal** [comment]
@totalo That's right. The action only [switches](https://github.com/ad-m/github-push-action/blob/master/start.sh#L41) the directory and executes the push command inside this folder. It's necessary that you beforehand add your changes to git.

**Comment by totalo** [comment]
> 

Ok, I see. Thank you for your patience.

**Comment by totalo** [comment]
> @totalo That's right. The action only [switches](https://github.com/ad-m/github-push-action/blob/master/start.sh#L41) the directory and executes the push command inside this folder. It's necessary that you beforehand add your changes to git.

Ok, I see. Thank you for your patience.
