### ISSUE TITLE
Feature Request: Push only the tag, not branch

### ISSUE THREAD

**Issue by ibexa-yuna** [ad-m/github-push-action#153]
Hi,

I'm trying to utilize this action as the last step in my release workflow.
As part of that workflow I need to push only the tag, as I have no need for a separate branch, but also I would like not to have tags on the branch I'm making it, as this branch is a "skeleton one" i.e. requires preparation before tagging, thus tags on it don't look good.

I'm reading the `start.sh` code and it seems there is no way to push just the tag I've just created, without pushing the branch.

https://github.com/ad-m/github-push-action/blob/master/start.sh#L52
`HEAD:$INPUT_BRANCH` is a branch notation, thus even if I input `branch` as my tag I will actually push both my tag and a branch with the same name as my tag.

**Comment by ZPascal** [comment]
Hi @ibexa-yuna, I understand the case and it sounds valid. Do you wanna handle it on your own and contribute it back to this repository or should I prepare the corresponding small PR?

**Comment by ibexa-yuna** [comment]
I would appreciate the 2-nd option, as I will not be able to replicate the same coding style as you have.

**Comment by ZPascal** [comment]
Okay @ibexa-yuna, I think I can prepare the new feature in the next few days.
