### ISSUE TITLE
failed to push due to "dubious ownership" of directory

### ISSUE THREAD

**Issue by dazinator** [ad-m/github-push-action#158]
![image](https://user-images.githubusercontent.com/3176632/220689819-0a9a0b4f-c247-491e-9b47-b3951bc6a288.png)

This github push action has recently stopped working.
Git is complaining about dubious ownership of a directory or something. See screenshot..

**Comment by ZPascal** [comment]
Hi @dazinatorm,  please switch to the `checkout@v3`and also to the `ad-m/github-push-action@master` version. That should solve your issue.

**Comment by ZPascal** [comment]
Hi @dazinator, can we close the issue?

**Comment by dazinator** [comment]
Sure, I havent tested yet but I will re-open or comment if it doesn't solve it! thank you!
