### ISSUE TITLE
Node v12 to v16

### ISSUE THREAD

**Issue by binaryshrey** [ad-m/github-push-action#159]
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: ad-m/github-push-action@v0.6.0. 
For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.

**Comment by ZPascal** [comment]
Hi @binaryshrey, the issue is already [fixed](https://github.com/ad-m/github-push-action/pull/140). Please switch the used version to `ad-m/github-push-action@master`.
