### ISSUE TITLE
Release new version?

### ISSUE THREAD

**Issue by siddharthvp** [ad-m/github-push-action#162]
Can a new version be released? Then, users wouldn't be forced to use `@master` version of the action to avoid the bug fixed in this commit: https://github.com/ad-m/github-push-action/commit/6defe3bd9f0a0846636a7d99ab96ccc75f2c858b.

**Comment by ZPascal** [comment]
Hi @siddharthvp, you are aware that you can also use the `checkout@v3` action to [mitigate](https://github.com/actions/checkout/blob/8f4b7f84864484a7bf31766abe9204da3cbe65b3/src/git-source-provider.ts#L43) the issue. I've already opened an [PR](https://github.com/ad-m/github-push-action/pull/145) to roll out a solution to create the new versions on a smother way, but I'm still waiting for a review.

**Comment by ZPascal** [comment]
**FYI:** I've manually released two new versions. v0.7.0 uses Node16 and v0.8.0 Node20 as JS runtime.
