### ISSUE TITLE
GITHUB_TOKEN not working

### ISSUE THREAD

**Issue by 8MiYile** [ad-m/github-push-action#163]
Hi guys, can you help me to check the error type of these two Actions?
https://github.com/8Mi-Tech/CefDetectorX/actions/runs/4697499882/jobs/8328725776
https://github.com/8Mi-Tech/MCCustomSkinLoader/actions/runs/4697401819/jobs/8328726589
```
 ! [remote rejected] HEAD -> <branch_name> (refusing to allow a GitHub App to create or update workflow `<another_workflow_file>` without `workflows` permission)
```

**Comment by ZPascal** [comment]
Hi @8MiYile, I think you've missed specifying the right access rights. Please follow this [example](https://github.com/ad-m/github-push-action/issues/96#issuecomment-1396347833) to reconfigure the permissions.

**Comment by 8MiYile** [comment]
My Action is executed on Fork Repo, so that means about this part, what permissions should be added inside the file so that it can be pushed directly?

**Comment by ZPascal** [comment]
Do you want to push inside the upstream part or inside your forked repository?

**Comment by 8MiYile** [comment]
It doesn't matter, I've finished fixing it
PAT Yes

**Comment by ZPascal** [comment]
Great to hear that everything works now as expected. A PAT is mostly the recommended solution, to handle access issues.
