### ISSUE TITLE
Add support for --tags

### ISSUE THREAD

**Issue by sormuras** [ad-m/github-push-action#17]
It would also be nice, if `tags: true` (default: `false`) could be configured.

_Same same as #2, but different._

**Comment by sormuras** [comment]
Trying another solution: `git config --local push.followTags true`

**Comment by sormuras** [comment]
https://github.com/ad-m/github-push-action/blob/0f7258526c7eb54ab64503a7ad3cdc68d4b94f08/start.sh#L24

**Comment by Woile** [comment]
I've tried this and it doesn't work.

My tag is being created but not pushed, any idea why? :(
 https://github.com/Woile/test-github-actions/blob/master/.github/workflows/bumpversion.yml
