### ISSUE TITLE
Protocol "https:" not supported. Expected "http:"

### ISSUE THREAD

**Issue by eullercdr** [ad-m/github-push-action#177]
Dears, 

Today i am facing this problem in action.

Can you help me?

![image](https://github.com/ad-m/github-push-action/assets/28054033/550728da-a3d4-4e64-aefd-9c58483af385)

Regards

**Comment by ZPascal** [comment]
Hi @eullercdr, did you specify the "github_url" to https://github.com?

**Comment by ZPascal** [comment]
FYI @eullercdr I've [reverted](https://github.com/ad-m/github-push-action/pull/176) the corresponding change and set up a test case on my side to further analyze the case.

**Comment by eullercdr** [comment]
Hi @ZPascal 

Thank you for your help with the issue!
