### ISSUE TITLE
What minimal set of permissions are required in fine-grained tokens to force push to a protected branch?

### ISSUE THREAD

**Issue by yankeexe** [ad-m/github-push-action#179]
I have tested with different permissions on fine-grained tokens including: 
- contents: r/w
- pull requests: r/w
- administration: r/w
But still can't push to protected branch. 
---
Also Actions Permissions for the repo: 
<img width="818" alt="image" src="https://github.com/ad-m/github-push-action/assets/13623913/19491af5-7b5e-4ee7-8399-59c8ec1d524d">

**Comment by ZPascal** [comment]
Hi @yankeexe,

I created a test case and was able to push commits to the protected branch with the following PAT permissions. Be aware, the token was restricted on my test case to only push inside one specific repository and it's necessary that the corresponding user got access rights to the repository.
- Contents r/w
- Metadata r
- Workflow r/w (These permissions are related to my test case and should not be necessary)

![PAT_Minimal_Permissions_Set](https://github.com/ad-m/github-push-action/assets/13447634/531cda0e-8e6c-41fd-bc73-a954b1a4b1fa)

**Comment by yankeexe** [comment]
@ZPascal thanks for the reply, but it didn't work in my case. The protected branch has another restriction of having to have a Pull Request before it can be merged. Are there any permissions that I can use for that?

**Comment by ZPascal** [comment]
Do you want to push directly to the protected branch without any PR? That's only possible with an Admin PAT.

**Comment by yankeexe** [comment]
Ohh ok gotcha. Thanks @ZPascal!
