### ISSUE TITLE
Action still uses node12 which is deprecated

### ISSUE THREAD

**Issue by kdambekalns** [ad-m/github-push-action#183]
Using this leads to

> The following actions uses node12 which is deprecated and will be forced to run on node16: ad-m/github-push-action@v0.6.0. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/

**Comment by kdambekalns** [comment]
This was something I reported already in and fixed with https://github.com/ad-m/github-push-action/pull/140

Now, if we could have a release of that, that would be great… 🫶

**Comment by ZPascal** [comment]
It's possible to use the `ad-m/github-push-action@master` version to mitigate the issue. I think's also a good idea to create a new release version, but the follow-up [PR](https://github.com/ad-m/github-push-action/pull/145) to handle tags automatically is still not reviewed. I think, it's necessary to create manually a new release version and I'll perform that asap.

**Comment by ZPascal** [comment]
@kdambekalns I think, I'll also update the version of Node directly to 20, because 16 is in the meantime also [deprecated](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/).

**Comment by ZPascal** [comment]
Hi @kdambekalns, FYI I've created two new releases v0.8.0 -> Node20 and v0.7.0 -> Node16.
