### ISSUE TITLE
Can we have a release which still using node16 

### ISSUE THREAD

**Issue by sushovan23** [ad-m/github-push-action#185]
Our runners are still not running latest os which supports node20. Can we have a release created which we can use instead of master to point to node16 for now?

**Comment by ZPascal** [comment]
@sushovan23 Do you need an official marketplace release or is one tag enough?

**Comment by sushovan23** [comment]
Right now im using ad-m/github-push-action@master
I see latest tag being ad-m/github-push-action@v0.6.0 
so if you can add another tag which supports node16 i can use that

**Comment by ZPascal** [comment]
**FYI:** I created a new [release](https://github.com/ad-m/github-push-action/releases/tag/v0.7.0) (v0.7.0) that uses Node16.
