### ISSUE TITLE
Missing input       uses: ad-m/github-push-action@master       with:         github_token: ${{ secrets.GH_TOKEN }}

### ISSUE THREAD

**Issue by zjt666666zjt** [ad-m/github-push-action#187]
commit
    - name: commit file
      run: |
        git config --local user.email 'github-actions[bot]@users.noreply.github.com'
        git config --local user.name 'github-actions[bot]'
        git diff --exit-code || git add . && git commit -am '[bot] update images.json' --allow-empty
    # push 
    - name: push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GH_TOKEN }} but  when I act this GitHub action   

##[debug]Evaluating condition for step: 'push changes'
##[debug]Evaluating: success()
##[debug]Evaluating success:
##[debug]=> true
##[debug]Result: true
##[debug]Starting: push changes
##[debug]Loading inputs
##[debug]Evaluating: secrets.GH_TOKEN
##[debug]Evaluating Index:
##[debug]..Evaluating secrets:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'GH_TOKEN'
##[debug]=> null
##[debug]Result: null
##[debug]Evaluating: github.server_url
##[debug]Evaluating Index:
##[debug]..Evaluating github:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'server_url'
##[debug]=> 'https://github.com/'
##[debug]Result: 'https://github.com/'
##[debug]Loading env
Run ad-m/github-push-action@master
Push to branch main
Missing input "github_token: ${{ secrets.GITHUB_TOKEN }}".
Error: Invalid exit code: 1
    at ChildProcess.<anonymous> (/home/runner/work/_actions/ad-m/github-push-action/master/start.js:30:21)
    at ChildProcess.emit (node:events:514:28)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5) {
  code: 1
}
##[debug]Node Action run completed with exit code 255
##[debug]Finishing: push changes##[debug]Evaluating condition for step: 'push changes'
##[debug]Evaluating: success()
##[debug]Evaluating success:
##[debug]=> true
##[debug]Result: true
##[debug]Starting: push changes
##[debug]Loading inputs
##[debug]Evaluating: secrets.GH_TOKEN
##[debug]Evaluating Index:
##[debug]..Evaluating secrets:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'GH_TOKEN'
##[debug]=> null
##[debug]Result: null
##[debug]Evaluating: github.server_url
##[debug]Evaluating Index:
##[debug]..Evaluating github:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'server_url'
##[debug]=> 'https://github.com/'
##[debug]Result: 'https://github.com/'
##[debug]Loading env
Run ad-m/github-push-action@master
Push to branch main
Missing input "github_token: ${{ secrets.GITHUB_TOKEN }}".
Error: Invalid exit code: 1
    at ChildProcess.<anonymous> (/home/runner/work/_actions/ad-m/github-push-action/master/start.js:30:21)
    at ChildProcess.emit (node:events:514:28)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5) {
  code: 1
}
##[debug]Node Action run completed with exit code 255
##[debug]Finishing: push changes

I don’t know how to deal with it.

**Comment by ZPascal** [comment]
Could you please specify the `GITHUB_TOKEN` as used secret name or have you set a custom secret? FYI: I think the default variable `GH_TOKEN` is only available inside the GH CLI.



```
- name: Push changes
  uses: ad-m/github-push-action@master
  with:
    github_token: ${{ secrets.GITHUB_TOKEN }}
```

**Comment by zjt666666zjt** [comment]
thanks for reply. I am a college stduent and I use it for the first time.  I can confirm that I have added secrets.

**Comment by ZPascal** [comment]
Hi @zjt666666zjt, I need a bit more context and information. Could you please share a screenshot of the secrets section of the repository, the expected case, the scope and rights of the custom token, and the workflow file? 

Is the repository-scoped [default token](https://docs.github.com/en/actions/security-guides/automatic-token-authentication) (GITHUB_TOKEN) not the best case for you? For this, it's also not necessary to define any GH token-related secrets.

**Comment by zjt666666zjt** [comment]
_**ok, my 'GITHUB_TOKEN'  is from the 'Personal access tokens (classic)' in the setting.   and in this repository . I have add a Dependabot secrets  named 'GH_TOKEN'  and put the'Personal access tokens (classic)'in to this secret**_

name: Auto Update Bing Images CI

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"
  push:
    branches: [ gh-pages ]
  pull_request:
    branches: [ gh-pages ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # checkout
    - name: checkout
      uses: actions/checkout@v2
    # setup nodejs
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
    - run: node ./assets/js/bing.js
    # commit
    - name: commit file
      run: |
        git config --local user.email 'github-actions[bot]@users.noreply.github.com'
        git config --local user.name 'github-actions[bot]'
        git diff --exit-code || git add . && git commit -am '[bot] update images.json' --allow-empty
    # push 
    - name: push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GH_TOKEN }}


_**this is my github action file . name is main.yml
when it run the last step always notices me  that the**_


##[debug]Evaluating condition for step: 'push changes'
##[debug]Evaluating: success()
##[debug]Evaluating success:
##[debug]=> true
##[debug]Result: true
##[debug]Starting: push changes
##[debug]Loading inputs
##[debug]Evaluating: secrets.GH_TOKEN
##[debug]Evaluating Index:
##[debug]..Evaluating secrets:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'GH_TOKEN'
##[debug]=> null
##[debug]Result: null
##[debug]Evaluating: github.server_url
##[debug]Evaluating Index:
##[debug]..Evaluating github:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'server_url'
##[debug]=> 'https://github.com'
##[debug]Result: 'https://github.com'
##[debug]Loading env
Run ad-m/github-push-action@master
Push to branch main
Missing input "github_token: ${{ secrets.GITHUB_TOKEN }}".
Error: Invalid exit code: 1
    at ChildProcess.<anonymous> (/home/runner/work/_actions/ad-m/github-push-action/master/start.js:30:[2](https://github.com/zjt666666zjt/zjt666666zjt.github.io/actions/runs/6806552597/job/18525346626#step:6:2)1)
    at ChildProcess.emit (node:events:514:28)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:[3](https://github.com/zjt666666zjt/zjt666666zjt.github.io/actions/runs/6806552597/job/18525346626#step:6:3)0[5](https://github.com/zjt666666zjt/zjt666666zjt.github.io/actions/runs/6806552597/job/18525346626#step:6:5):5) {
  code: 1
}
##[debug]Node Action run completed with exit code [25](https://github.com/zjt666666zjt/zjt666666zjt.github.io/actions/runs/6806552597/job/18525346626#step:6:25)5
##[debug]Finishing: push changes

**Comment by ZPascal** [comment]
A Dependabot secret is not available inside workflows. If you want to specify the custom token (PAT), it's necessary to add them to the Action section. For me, your case is still not clear. Do you want to push to the same repository or another repository? Is a branch protection rule active? Why it's necessary to use a PAT?

I recommend to try [this](https://github.com/ad-m/github-push-action/issues/187#issuecomment-1797907596) corresponding settings out.

**Comment by zjt666666zjt** [comment]
So what should I do to keep the workflow running. The is very important for me. I am not clearly what should I do.  I am comfused.

**Comment by ZPascal** [comment]
@zjt666666zjt You should follow the following steps to handle it on your side:

1. Follow this [link](https://github.com/ad-m/github-push-action/issues/96#issuecomment-1517328108) and set the GitHub Action workflow permissions to allow pushes to the repository
2. Replace your GH Action push command inside your workflow file with the following code block and use the default token
```
- name: Push changes
  uses: ad-m/github-push-action@master
  with:
    github_token: ${{ secrets.GITHUB_TOKEN }}
```
3. Delete the custom token with the name `GH_TOKEN` inside the secrets section

I'll close this case now, feel free to reopen the case, if necessary.
