### ISSUE TITLE
How can this action push without write permission?

### ISSUE THREAD

**Issue by szepeviktor** [ad-m/github-push-action#189]
```
github_token: ${{ github.token }}
```
By default `github.token` has
```
permissions:
  contents: read
```
How can this action push without write permission?

I've tried to execute `git push` in a workflow and it failed without `content: write` permission.
Please help me understand this.

**Comment by ZPascal** [comment]
Hi @szepeviktor, have you specified the settings within the repository (Settings -> Action -> General -> Workflow permissions -> Read and write permissions) that it is generally possible to push in the repository via GH actions?

**Comment by szepeviktor** [comment]
Thank you very much for your answer.

I have safe settings there.

![image](https://github.com/ad-m/github-push-action/assets/952007/1f9eb6ed-a226-4149-8dac-3dfb99d56dee)

**Comment by szepeviktor** [comment]
Please consider adding this requirement to README.
