### ISSUE TITLE
Faster build

### ISSUE THREAD

**Issue by estensen** [ad-m/github-push-action#19]
I've been using this action for some time and it consistently builds in ~17 seconds. Any idea of how we can make it faster?

**Comment by ad-m** [comment]
We build almost nothing ( https://github.com/ad-m/github-push-action/blob/master/Dockerfile ). If we build earlier, then probably the build time will be similar to the time of downloading a new image from the image register.

**Comment by tenhobi** [comment]
Yea, caching will solve a lot for many plugins I believe.

**Comment by ad-m** [comment]
At this stage, I don't see any way to optimize build time of action more. Any acceleration of the process can only be done by GitHub (parallel building of multiple actions, cache, etc.). 

Nevertheless, any suggestions for changes in this project in the form of pull requests are welcome.

**Comment by paced** [comment]
A major speed improvement can come from #26: using the JS syntax instead of a Dockerfile. The VMs have `git` preinstalled so it's simply running the `.sh` file except with use of `child-process` or similar.

**Comment by ad-m** [comment]
@paced, thanks! Build time eliminated at all ( https://github.com/ad-m/github-push-action/commit/1a31adf02b58ca9a3b97be74658133d993a352e1/checks?check_suite_id=307492470 ). Action execute in about 1 second!

**Comment by tenhobi** [comment]
Hey, there might be a caching solution now https://github.com/actions/cache

**Comment by ad-m** [comment]
@tenhobi , there is no cache solution for build of actions, see actions/cache#81.
