### ISSUE TITLE
remote: Invalid username or password. fatal: Authentication failed for 'repository'

### ISSUE THREAD

**Issue by CrafterKolyan** [ad-m/github-push-action#21]
Triggers on this test suite (see Equality test -> Push changes):
https://github.com/CrafterKolyan/mmp-practicum-sql-fall-2019/commit/fec767484cd65bef7564526340b6e2685f5a91fc/checks?check_suite_id=270034433

Works perfectly for (see Equality test -> Push changes):
https://github.com/CrafterKolyan/mmp-practicum-sql-fall-2019/commit/a40d5ea52e0ba5c5075ae1a4ad51bc133ead1fd7/checks?check_suite_id=270116816

The only real difference between this 2 test suites is that first was working for more than 1 hour, while 2nd one done his job in 5 minutes. I used github push action @ `master`. Will change to `v.0.4.0` to see if this bug will occur again.

Is this known bug?

**Comment by ad-m** [comment]
I am afraid that this is not a problem on the part of our action, but on the side of GitHub Actions, which assigns a token for build that is only valid for one hour and does not verify the live-time of the build.

See https://help.github.com/en/articles/virtual-environments-for-github-actions#github_token-secret how to obtain different type of auth token to avoid situation like that.

@rachmari, if I understand correctly, you are responsible for the documentation. What do you think about documenting the validity period of a token automatically created by GitHub Actions for a specific build? Documentation mentioned above does not specify how long token is valid.

**Comment by rachmari** [comment]
@ad-m thanks for the ping! 🙌 

I did confirm with the engineering team that the `GITHUB_TOKEN` expires 60 minutes after a job begins. I've created a tracking issue to update this in the docs. 🙇‍♀
