### ISSUE TITLE
How to set GITHUB_TOKEN?

### ISSUE THREAD

**Issue by Glusk** [ad-m/github-push-action#23]
I'm confused as to how to pass the `GITHUB_TOKEN` to your action. Is it as simple as adding a new  *Personal access token* to `settings -> tokens -> Personal access tokens` to my GitHub account? ^^

**Comment by tenhobi** [comment]
The `GITHUB_TOKEN` is provided by GitHub itself. You don't have to do anything. 👍 

For other tokens, for example, to some app, you would provide it using Personal access tokens.

**Comment by koppor** [comment]
@Glusk2 You can add a text to the README.md.

**Comment by Glusk2** [comment]
So I simply take an OAuth token (generated on GitHub via *Personal access token* util or provided by a third party service) and copy it to my **secrets** store, refering to it as `${{ secrets.<my_awesome_token>}}` ?

**Comment by tenhobi** [comment]
@Glusk2 for thirth party services that is correct – you have to add the key to `Personal access tokens` and you can use it like `secrets.<my_token>`.

GitHub automatically provides `secrets.GITHUB_TOKEN` for you.

---

For more information, read https://help.github.com/en/github/automating-your-workflow-with-github-actions/virtual-environments-for-github-actions#creating-and-using-secrets-encrypted-variables

**Comment by ZPascal** [comment]
I'm closing the issue because I think the use of tokens, permissions, and secrets is already documented [here](https://github.com/ad-m/github-push-action/Readme.md#requirements-and-prerequisites) and in the GitHub upstream documentation. Feel free to reopen it if needed.
