### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by tenhobi** [ad-m/github-push-action#3]
It would be nice to add a documentation about what inputs people can use, for not it's probably `github_token` and `branch`, might be `force` (#2) etc. in the future.

👍

**Comment by ad-m** [comment]
I like this idea. Pull requests are welcome. Would you like to prepare a pull requests for that? Do you need help or information?

BTW. GitHub should provide such documentation automatically based on the prepared manifesto.

**Comment by tenhobi** [comment]
Yeah, it would be nice if GitHub would generate an input list preview from the [action.yml](https://github.com/ad-m/github-push-action/blob/master/action.yml). For now I don't see it anywhere, so we should add it to make this plugin more clear.

I will make a PR tonight. 👍
