### ISSUE TITLE
bash: start.sh: No such file or directory

### ISSUE THREAD

**Issue by simon300000** [ad-m/github-push-action#30]
I guess the reason might be related to the recent commits which switch from start.sh to start.js something.

Run: https://github.com/dd-center/vdb/commit/8beb4a07bf35596261bd8cd99774133369c4076b/checks?check_suite_id=307756186#step:5:6

Config: https://github.com/dd-center/vdb/blob/8beb4a07bf35596261bd8cd99774133369c4076b/.github/workflows/nodejs-cd.yml#L21

Maybe in the readme, do not suggest users to use `ad-m/github-push-action@master`, but a specific version such as `ad-m/github-push-action@v0.5.0`

**Comment by ad-m** [comment]
Thank you for the information. In my opinion, the "master" branch should always be in good condition, and tests should catch such situations. However, in this case they proved to be insufficient. If you use release, there is also the risk of creating an incorrect release. 

I'm starting work on a fix.

**Comment by simon300000** [comment]
Now it is fixed, thanks!
