### ISSUE TITLE
Push not triggering workflow

### ISSUE THREAD

**Issue by FelipeRRM** [ad-m/github-push-action#32]
I have two branches in my repo, "master" and  "branch2". I also have two separate workflows, one for each branch, and each of them is triggered by a push on that specific branch. The thing is that I am using this action here inside master's workflow to push some changes to "branch2". The push is working very well, but the problem is that it is not triggering the workflow on "branch2" as it should, while pushing manually from github does. What might be the issue?

**Comment by ad-m** [comment]
Yes, push using standard GitHub Token not trigger workflow. It is GitHub design to avoid infinity triggers loop.

**Comment by ad-m** [comment]
Push and any other actions by GitHub Action eg.comments not trigger GitHub Action.

**Comment by FelipeRRM** [comment]
Oh I see, any tips on how to circumvent this limitation then? I see that they don't want infinite triggers but it is also very limiting at the same time.

**Comment by ad-m** [comment]
I don't tested, but let's try Personal Access Token in GitHub Action.

**Comment by FelipeRRM** [comment]
@ad-m it worked! When using a personal token to push instead of the default GitHub Token available in the action it triggers the other workflow! Amazing!

**Comment by rokroskar** [comment]
Does this still work? I have a workflow where I push with a private access token and it doesn't seem to trigger a new CI build. Maybe github changed the behavior?

**Comment by Kubitomakita** [comment]
For some reason pushing with personal token works in one of my repositories, but not the other. Config seems to be the same

**Comment by rokroskar** [comment]
@Kubitomakita if you are using the checkout action, try giving it your PAT as well.

**Comment by Kubitomakita** [comment]
Thanks for the hint @rokroskar !

Turned out it works as expected with `actions/checkout@v1` but not with `actions/checkout@v2`. This applies to the action which is making the change.

**Comment by rokroskar** [comment]
So giving the PAT to `actions/checkout@v2` fixes the problem? Or are you saying that it is still persisting?

**Comment by Kubitomakita** [comment]
Haven't testing giving PAT to `actions/checkout@v2` but downgrading to `actions/checkout@v1` works without PAT passed to this step

**Comment by rokroskar** [comment]
Ah ok - because I think in `v2` they changed how the credentials are stored, and I think it overrides the PAT passed to the push action.

**Comment by paulhenri-l** [comment]
I can confirm that using the PAT in the `actions/checkout@v2` action fixes the issue 👍🏻
