### ISSUE TITLE
Push action not working for fork branch

### ISSUE THREAD

**Issue by acoop133** [ad-m/github-push-action#40]
Hi, 
forgive my retardedness.

someone made a fork of my repo to make a contribution. They've made a PR on my repo and the push action fails with the following error.

```
Run ad-m/github-push-action@master
  with:
    github_token: ***
    branch: patch-1
    directory: .
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.7.5/x64
Started: bash /home/runner/work/_actions/ad-m/github-push-action/master/start.sh
Push to branch patch-1
remote: Permission to DarkThemeHub/GithubDarkTheme.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/DarkThemeHub/GithubDarkTheme.git/': The requested URL returned error: 403
```

The script works fine if its a PR created from a branch in origin.
I feel like the error isnt actually correct since it works fine for branches in origin repo. 

~Is this just the case that i have to include github-actions[bot] as a contributor to get it working with a PR from a forked branch?~

Or is it the case that forked branch's action is trying to push to a branch in origin which does not exist?

Or is it something else?

```name: GenerateStylusTestFile

on: [pull_request]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with: 
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Generate test style
      run: |
        python Scripts/GenerateStylusTestFile.py
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Generate Test Style Files" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.head_ref }}
```

**Comment by acoop133** [comment]
Just checked if i can add `github-actions` as a contributor.   thats a no

**Comment by ad-m** [comment]
Why do you want untruste code (pushed by anybody) to have the right to modify any branch of your repository before you evaluate it? If you want the code to be modified by linter then it should probably be modified in the source repository, and you have created the PR with the result only.

**Comment by acoop133** [comment]
Im not giving them rights to modify any branch of my reposity, the point of the action is any push to a PR will generate a test file to allow easy testing of the style. 
I just want it run on their own branch. I obviously look through the changes before i test it.

**Comment by acoop133** [comment]
hence `branch: ${{ github.head_ref }}`

**Comment by acoop133** [comment]
hmmm i've possibly miss used `github.head_ref`

**Comment by ad-m** [comment]
Configuration ```branch: ${{ github.head_ref }}``` is not related to permission at all. Token provided by GitHub for worker for pull requests does not have any write access to protect abusing that token.

**Comment by ad-m** [comment]
See https://help.github.com/en/actions/automating-your-workflow-with-github-actions/authenticating-with-the-github_token#permissions-for-the-github_token :
![obraz](https://user-images.githubusercontent.com/3618479/70963522-0255b080-2089-11ea-8abd-ad28165e23f0.png)

**Comment by acoop133** [comment]
though in my situation its my action needing to push to their fork branch, not their action trying to push to my repo.

i'd expect my the actions to have write access to incoming pr branches. 

Anyway, since the issue is not related to `github-push-action` im going to leave you be now :)

**Comment by janosh** [comment]
@Snazzie Did you end up finding a way to push to incoming PR branches coming from a fork?

**Comment by Snazzie** [comment]
@janosh I haven't looked any further into it, sorry.
