### ISSUE TITLE
No 'git add . ' required in "Commit files" sections? 

### ISSUE THREAD

**Issue by khoivan88** [ad-m/github-push-action#49]
Hi, thank you for a very useful action. I am new to GitHub action do i just want to ask about the example usage you have. I noticed that there is no `git add .` in the section for 'Commit file'. Is that because you have the `-a` in the `git commit... `. Thank you very much for your help!

**Comment by ad-m** [comment]
There is no ```git add .````, because there is ```-a``` in the ```git commit```. ```git add .``` will add all files (including new files) to Git, in contrast to ```git commit -a``` which will add modified files to git-known files (the file must be previously known by git, so it cannot be new).

**Comment by khoivan88** [comment]
Thank you very much for explaining it to me. I really appreciate it.
