### ISSUE TITLE
Will this cause infinite loop if I use this to push to same repository?

### ISSUE THREAD

**Issue by jaibatrik** [ad-m/github-push-action#70]
If I use this action on push to master and use it to push to same repository, will it cause an infinite loop? If it does, is there a recommended strategy to avoid it?

For context, my use case is, in my repo, which is an Angular app, I want to build and deploy the app to `/docs` path once I push changes to the app.

> PS - I totally understand that this is not an issue with the library and is a question; since there's no forum like Gitter / Slack for this repo, raising an issue here for attention.

**Comment by ad-m** [comment]
>  I totally understand that this is not an issue with the library and is a question; since there's no forum like Gitter / Slack for this repo, raising an issue here for attention.

No problem.

> If I use this action on push to master and use it to push to same repository, will it cause an infinite loop?

As long as you use default GitHub Actions token i's safe from infinite loop, becasuse default GitHub Actions token does not trigger GitHub Actions.

**Comment by jaibatrik** [comment]
That helps, thank you!
