### ISSUE TITLE
HELP THIS  Please!

### ISSUE THREAD

**Issue by lswlover2579** [ad-m/github-push-action#78]
why this?how to solve?
```
Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	modified:   Series.m3u

[main 88744d7] PUSH TO Add changes
 1 file changed, 9 insertions(+), 1 deletion(-)
remote: Repository not found.
```

**Comment by lswlover2579** [comment]
I just fix it by correct use user/repo....

**Comment by ad-m** [comment]
Do you have still that issue?

Could you provide your workflow file?

**Comment by lswlover2579** [comment]
No I’m over it
I’ll put the file when I free

**Comment by ad-m** [comment]
Are yo use private repository? Did you pass GitHub Token?

**Comment by lswlover2579** [comment]
public 
and have used token

**Comment by lswlover2579** [comment]
`name: VideoParse2

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
    - cron: '0 4,16 * * *'
  watch:
    type: [started]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      # Runs a set of commands using the runners shell
      - name: 'Install requirements'
        run: pip install -r ./requirements.txt
        
      - name: '运行【VideoParse】' 
        run: python3 VideoParse.py

      - name: 'Commit files'
        run: |
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git config --local user.name "$GITHUB_ACTOR"
          git add .
          git status
          git commit -m "PUSH TO Add changes" -a
          git push -f https://${{ secrets.PAT }}@github.com/lswlover2579/PyCrawlers.git
      - name: 'Push changes'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PAT }}
          branch: ${{ github.head_ref }}`
I have a doubt.
 how to modify when i need the commit files reset instead of  merge of same name repo file previous created?
i don't really know git
please show code  thx

**Comment by lswlover2579** [comment]
lol  
I read a llittle git tutorial and finally kick the question!
