### ISSUE TITLE
question about design

### ISSUE THREAD

**Issue by setop** [ad-m/github-push-action#94]
If I get it well, there is an action that is launching a NodeJS script that is launching a bash script that is invoking git command ?
Sounds complex architecture, what is the rational ?

**Comment by ad-m** [comment]
See #26

**Comment by setop** [comment]
thanks for the quick and relevant reply.

do you have any idea why node runner are faster than docker runner and if it is still the case (#26 was raised one year and a half ago) ?

**Comment by ad-m** [comment]
There is no seperate runner for Node and Docker, but there is separate action type.

Docker actions require building for workflow runs. On cloud hoster runner each run is started in fresh virtual machine from golden image ( https://github.com/actions/virtual-environments/ ), so building Docker action require pull base Docker image into virtual machine.

NodeJS actions reuse existing tools in golden images. Golden images have already NodeJS and git pre-cached, so no pulling any tools for each workflow run.

**Comment by setop** [comment]
Very clear, thanks for the explanation.
